### ISSUE TITLE
What's in v1.0.4?

### ISSUE THREAD

**Issue by dahlbyk** [arex388/Arex388.AspNet.Mvc.Startup#3]
Noticed you published [v1.0.4](https://www.nuget.org/packages/Arex388.AspNet.Mvc.Startup/1.0.4) to the NuGet Gallery, but there aren't any recent changes in the repo.

**Comment by arex388** [comment]
- Updated `Microsoft.Extensions.DependencyInjection` to 5.0.1.
- Updated `Microsoft.Extensions.DependencyInjection.Abstractions` to 5.0.0.
- Updated `Microsoft.Owin` to 4.2.0.
- Renamed `Arex388.AspNet.Mvc.Startup.Extensions` namespace to `Arex388.AspNet.Mvc.Startup`. I just wanted to use the `Extensions` as folder, not as a namespace...
- Apparently cleaned up whitespace...

It was mostly an update to update dependencies because I was holding back on updating dependencies in my project and finally got fed up with the list of updates staring back at me on NuGet... And I forgot to update the repository.

I see that you added a pull request, but I have to admit, I'm a simpleton when it comes to using GH properly and I have no idea how to reconcile my pending update to the repository and your pull request. Can you guide me on what I should do? Update the repository and then accept the commit, although the commit might break because of my changes?

**Comment by dahlbyk** [comment]
Go ahead and push your changes to master. If there's a conflict or anything breaks, I will update my branch.

And again, if you would prefer to just have this project be your sandbox to solve your problems, I can spin up a separate project to try out my larger ideas.

**Comment by arex388** [comment]
Repository is updated.

It's not so much doing my own thing, but more so being spread very thin on time these days. I just need to make sure I'm more on top of things with the repository. I'd rather changes go through here so that we all (well, at least the two of us) can benefit from the improvements.
