### ISSUE TITLE
Proposal: Breaking Change on Configure(IAppBuilder)

### ISSUE THREAD

**Issue by arex388** [arex388/Arex388.AspNet.Mvc.Startup#6]
In #4 @dahlbyk showed how he configures HangFire using the current version, and I finally got around to updating my app with it and decided to update how I configure HangFire as well (mostly because it was erroring out now).

After ripping out my implementation and loosly copying his version, which was very similar to how I configure HangFire in my other .NET 5 project, I realized there's an opportunity for an improvement, but that it will be a breaking change.

Currently we have `Configure(IAppBuilder app)` which is being called by `Configuration(IAppBuilder app)`. It only passes in `IAppBuilder` even though at this point we also have full access to `IServiceProvider`.

I propose that we change the signature to `Configure(IAppBuilder app, IServiceProvider provider)` instead and remove the previous signature or obsolete it as a compilation error. The reason for this is because I like to make extension methods for `IServiceCollection` and `IAppBuilder`, and even extract them out into separate projects. Because with HangFire there's the issue where you have to activate the `IGlobalConfiguration` before calling `UseHangfireServer()` you have to be able to call into `IServiceProvider`.

You can call into `StartupApplication.ServiceProvider` instead since it's static, but that just doesn't sit well with me.

From what I understand, ASP.NET Core does some black magic stuff to figure out what the method signature is expecting and will just inject things, but here we don't really have the time and I imagine desire to create our own black magic. If we change the signature we cover both use cases, even if `IServiceProvider` is never actually used.

@dahlbyk can I get you thoughts on this?

**Comment by dahlbyk** [comment]
Since the static `ServiceProvider` exists in the class that has `Configure(IAppBuilder)` and can be accessed unqualified, I don't really mind it. But making it explicitly available as a method parameter doesn't bother me.

To avoid a breaking change, you could mark the current method `[Obsolete]` to direct towards the new overload. Then just call both in `Configuration()`.

Or another option would be to add the `IServiceProvider` to `app.Properties` and provide a `GetServiceProvider()` extension method on `IAppBuilder`. I believe that would also make it available in the OWIN request `Environment`.

**Comment by arex388** [comment]
I really liked the extension method option so I went with that for v1.0.6.
